# Local MySQL Settings
environment: local

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_example #check IP address for the MySQL docker image
    username: dbuser
    password: testtest
    schema:
      classpath: schema.sql
    data:
      classpath: data.sql

  jpa:
    hibernate.ddl-auto: update
